spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      format_sql: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/mybankdb
    username: user
    password: pass
    driverClassName: org.postgresql.Driver

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yml