//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.29 at 09:06:06 PM GMT+04:00 
//


package mybankapp.ws.org.mybankapp.auth.wsdl;

import mybankapp.dto.AuthenticationRequestDTO;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="transactionDTO" type="{http://www.mybankapp.org/auth/wsdl}authenticationRequestDTO"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "transactionDTO"
})
@XmlRootElement(name = "loginRequest")
public class LoginRequest {

    @XmlElement(required = true)
    protected AuthenticationRequestDTO transactionDTO;

    /**
     * Gets the value of the transactionDTO property.
     * 
     * @return
     *     possible object is
     *     {@link AuthenticationRequestDTO }
     *     
     */
    public AuthenticationRequestDTO getTransactionDTO() {
        return transactionDTO;
    }

    /**
     * Sets the value of the transactionDTO property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthenticationRequestDTO }
     *     
     */
    public void setTransactionDTO(AuthenticationRequestDTO value) {
        this.transactionDTO = value;
    }

}
