//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.29 at 09:06:06 PM GMT+04:00 
//


package mybankapp.ws.org.mybankapp.news.wsdl;

import mybankapp.dto.NewsArticleDTO;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import java.net.URL;
import java.util.Date;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="newsArticleDTO" type="{http://www.mybankapp.org/news/wsdl}newsArticleDTO"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "title",
        "shorttext",
        "fulltext",
        "linktoimg",
        "buttonname",
        "isActual",
        "url"
})
@XmlRootElement(name = "addNewsArticleRequest")
public class AddNewsArticleRequest {

    @XmlElement(required = true)
    protected String title;
    @XmlElement(required = true)
    protected String shorttext;
    @XmlElement(required = true)
    protected String fulltext;
    @XmlElement(required = true)
    protected String linktoimg;
    @XmlElement(required = true)
    protected String buttonname;
    @XmlElement(required = true)
    protected Boolean isActual;
    @XmlElement(required = true)
    protected URL url;

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getShorttext() {
        return shorttext;
    }

    public void setShorttext(String shorttext) {
        this.shorttext = shorttext;
    }

    public String getFulltext() {
        return fulltext;
    }

    public void setFulltext(String fulltext) {
        this.fulltext = fulltext;
    }

    public String getLinktoimg() {
        return linktoimg;
    }

    public void setLinktoimg(String linktoimg) {
        this.linktoimg = linktoimg;
    }

    public String getButtonname() {
        return buttonname;
    }

    public void setButtonname(String buttonname) {
        this.buttonname = buttonname;
    }

    public URL getUrl() {
        return url;
    }

    public void setUrl(URL url) {
        this.url = url;
    }

    public Boolean getActual() {
        return isActual;
    }

    public void setActual(Boolean actual) {
        isActual = actual;
    }
}
