//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.29 at 09:06:06 PM GMT+04:00 
//


package mybankapp.ws.org.mybankapp.news.wsdl;

import mybankapp.dto.NewsArticleDTO;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.mybankapp.news.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _WatchNewsArticleResponse_QNAME = new QName("http://www.mybankapp.org/news/wsdl", "watchNewsArticleResponse");
    private final static QName _DeleteAccountResponse_QNAME = new QName("http://www.mybankapp.org/news/wsdl", "deleteAccountResponse");
    private final static QName _UnwatchNewsArticleResponse_QNAME = new QName("http://www.mybankapp.org/news/wsdl", "unwatchNewsArticleResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.mybankapp.news.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AddNewsArticleRequest }
     * 
     */
    public AddNewsArticleRequest createAddNewsArticleRequest() {
        return new AddNewsArticleRequest();
    }

    /**
     * Create an instance of {@link NewsArticleDTO }
     * 
     */
    public NewsArticleDTO createNewsArticleDTO() {
        return new NewsArticleDTO();
    }

    /**
     * Create an instance of {@link AddNewsArticleResponse }
     * 
     */
    public AddNewsArticleResponse createAddNewsArticleResponse() {
        return new AddNewsArticleResponse();
    }

    /**
     * Create an instance of {@link FindNewsArticleRequest }
     * 
     */
    public FindNewsArticleRequest createFindNewsArticleRequest() {
        return new FindNewsArticleRequest();
    }

    /**
     * Create an instance of {@link FindNewsArticleResponse }
     * 
     */
    public FindNewsArticleResponse createFindNewsArticleResponse() {
        return new FindNewsArticleResponse();
    }

    /**
     * Create an instance of {@link WatchNewsArticleRequest }
     * 
     */
    public WatchNewsArticleRequest createWatchNewsArticleRequest() {
        return new WatchNewsArticleRequest();
    }

    /**
     * Create an instance of {@link DeleteNewsArticleRequest }
     * 
     */
    public DeleteNewsArticleRequest createDeleteNewsArticleRequest() {
        return new DeleteNewsArticleRequest();
    }

    /**
     * Create an instance of {@link UnwatchNewsArticleRequest }
     * 
     */
    public UnwatchNewsArticleRequest createUnwatchNewsArticleRequest() {
        return new UnwatchNewsArticleRequest();
    }

    /**
     * Create an instance of {@link ShowNewsRequest }
     * 
     */
    public ShowNewsRequest createShowNewsRequest() {
        return new ShowNewsRequest();
    }

    /**
     * Create an instance of {@link ShowNewsResponse }
     * 
     */
    public ShowNewsResponse createShowNewsResponse() {
        return new ShowNewsResponse();
    }

    /**
     * Create an instance of {@link ShowArchiveRequest }
     * 
     */
    public ShowArchiveRequest createShowArchiveRequest() {
        return new ShowArchiveRequest();
    }

    /**
     * Create an instance of {@link ShowArchiveResponse }
     * 
     */
    public ShowArchiveResponse createShowArchiveResponse() {
        return new ShowArchiveResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.mybankapp.org/news/wsdl", name = "watchNewsArticleResponse")
    public JAXBElement<Object> createWatchNewsArticleResponse(Object value) {
        return new JAXBElement<Object>(_WatchNewsArticleResponse_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.mybankapp.org/news/wsdl", name = "deleteAccountResponse")
    public JAXBElement<Object> createDeleteAccountResponse(Object value) {
        return new JAXBElement<Object>(_DeleteAccountResponse_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.mybankapp.org/news/wsdl", name = "unwatchNewsArticleResponse")
    public JAXBElement<Object> createUnwatchNewsArticleResponse(Object value) {
        return new JAXBElement<Object>(_UnwatchNewsArticleResponse_QNAME, Object.class, null, value);
    }

}
