//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.29 at 09:06:06 PM GMT+04:00 
//


package mybankapp.ws.org.mybankapp.bank.wsdl;

import mybankapp.dto.CurrencyAccountDTO;
import mybankapp.dto.PersonDTO;
import mybankapp.dto.TransactionDTO;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.mybankapp.bank.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AddPersonResponse_QNAME = new QName("http://www.mybankapp.org/bank/wsdl", "addPersonResponse");
    private final static QName _GetAllPersonsRequest_QNAME = new QName("http://www.mybankapp.org/bank/wsdl", "getAllPersonsRequest");
    private final static QName _DeleteAccountResponse_QNAME = new QName("http://www.mybankapp.org/bank/wsdl", "deleteAccountResponse");
    private final static QName _DeletePersonResponse_QNAME = new QName("http://www.mybankapp.org/bank/wsdl", "deletePersonResponse");
    private final static QName _UpdatePersonResponse_QNAME = new QName("http://www.mybankapp.org/bank/wsdl", "updatePersonResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.mybankapp.bank.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AddPersonRequest }
     * 
     */
    public AddPersonRequest createAddPersonRequest() {
        return new AddPersonRequest();
    }

    /**
     * Create an instance of {@link GetPersonRequest }
     * 
     */
    public GetPersonRequest createGetPersonRequest() {
        return new GetPersonRequest();
    }

    /**
     * Create an instance of {@link GetPersonResponse }
     * 
     */
    public GetPersonResponse createGetPersonResponse() {
        return new GetPersonResponse();
    }

    /**
     * Create an instance of {@link PersonDTO }
     * 
     */
    public PersonDTO createPersonDTO() {
        return new PersonDTO();
    }

    /**
     * Create an instance of {@link GetAllPersonsResponse }
     * 
     */
    public GetAllPersonsResponse createGetAllPersonsResponse() {
        return new GetAllPersonsResponse();
    }

    /**
     * Create an instance of {@link AddAccountRequest }
     * 
     */
    public AddAccountRequest createAddAccountRequest() {
        return new AddAccountRequest();
    }

    /**
     * Create an instance of {@link CurrencyAccountDTO }
     * 
     */
    public CurrencyAccountDTO createCurrencyAccountDTO() {
        return new CurrencyAccountDTO();
    }

    /**
     * Create an instance of {@link AddAccountResponse }
     * 
     */
    public AddAccountResponse createAddAccountResponse() {
        return new AddAccountResponse();
    }

    /**
     * Create an instance of {@link GetPersonAccountsRequest }
     * 
     */
    public GetPersonAccountsRequest createGetPersonAccountsRequest() {
        return new GetPersonAccountsRequest();
    }

    /**
     * Create an instance of {@link GetPersonAccountsResponse }
     * 
     */
    public GetPersonAccountsResponse createGetPersonAccountsResponse() {
        return new GetPersonAccountsResponse();
    }

    /**
     * Create an instance of {@link GetAccountTransactionsRequest }
     * 
     */
    public GetAccountTransactionsRequest createGetAccountTransactionsRequest() {
        return new GetAccountTransactionsRequest();
    }

    /**
     * Create an instance of {@link GetAccountTransactionsResponse }
     * 
     */
    public GetAccountTransactionsResponse createGetAccountTransactionsResponse() {
        return new GetAccountTransactionsResponse();
    }

    /**
     * Create an instance of {@link TransactionDTO }
     * 
     */
    public TransactionDTO createTransactionDTO() {
        return new TransactionDTO();
    }

    /**
     * Create an instance of {@link DeleteAccountRequest }
     * 
     */
    public DeleteAccountRequest createDeleteAccountRequest() {
        return new DeleteAccountRequest();
    }

    /**
     * Create an instance of {@link DeletePersonRequest }
     * 
     */
    public DeletePersonRequest createDeletePersonRequest() {
        return new DeletePersonRequest();
    }

    /**
     * Create an instance of {@link UpdatePersonRequest }
     * 
     */
    public UpdatePersonRequest createUpdatePersonRequest() {
        return new UpdatePersonRequest();
    }

    /**
     * Create an instance of {@link AddTransactionRequest }
     * 
     */
    public AddTransactionRequest createAddTransactionRequest() {
        return new AddTransactionRequest();
    }

    /**
     * Create an instance of {@link AddTransactionResponse }
     * 
     */
    public AddTransactionResponse createAddTransactionResponse() {
        return new AddTransactionResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.mybankapp.org/bank/wsdl", name = "addPersonResponse")
    public JAXBElement<String> createAddPersonResponse(String value) {
        return new JAXBElement<String>(_AddPersonResponse_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.mybankapp.org/bank/wsdl", name = "getAllPersonsRequest")
    public JAXBElement<Object> createGetAllPersonsRequest(Object value) {
        return new JAXBElement<Object>(_GetAllPersonsRequest_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.mybankapp.org/bank/wsdl", name = "deleteAccountResponse")
    public JAXBElement<Object> createDeleteAccountResponse(Object value) {
        return new JAXBElement<Object>(_DeleteAccountResponse_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.mybankapp.org/bank/wsdl", name = "deletePersonResponse")
    public JAXBElement<Object> createDeletePersonResponse(Object value) {
        return new JAXBElement<Object>(_DeletePersonResponse_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.mybankapp.org/bank/wsdl", name = "updatePersonResponse")
    public JAXBElement<String> createUpdatePersonResponse(String value) {
        return new JAXBElement<String>(_UpdatePersonResponse_QNAME, String.class, null, value);
    }

}
